### ISSUE TITLE
希望能增加Scrapy版本的问题

### ISSUE THREAD

**Issue by NingerJohn** [Danielyan86/Movie-scrapy#1]
#### 纠结scrapy版本的说明，直接运行报错如下
* 报错1
```
from scrapy.selector import HtmlXPathSelector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'HtmlXPathSelector'
```
scrapy 1.7.0以后就删除了HtmlXPathSelector，我就装了1.6.0版本。
但是运行的时候，还是报错如下
* 报错2
```
File "/mnt/d/www/Movie-scrapy/movie/movie/spiders/mtime_spider.py", line 2, in <module>
    from scrapy.spider import BaseSpider
ModuleNotFoundError: No module named 'scrapy.spider'
```
所以希望能说明scrapy的版本号

#### 引申
我自己尝试写用scrapy抓取的时候，mtime经常会返回521，猜测是js cookie的验证问题。最终只能选择selenium。不知道库主的代码，是否会有这个问题？测试了，确实有这个问题
```
INFO: Ignoring response <521 http://movie.mtime.com/50004/>: HTTP status code is not handled or not allowed
```

#### 补充
经过了测试，python3下面，需要安装scrapy,pillow等，安装如下
```
pip3 install 'scrapy==1.5.2'
pip3 install pillow
pip3 install pymongo
```

**Comment by Danielyan86** [comment]
谢谢提醒。我测试了下，现在确实有521的问题，应该是Mtime
网站已经更新了，用requests包测试，在header上加上cookie可以拿到返回值。但是scrapy这边测试还没有通过，不知道你那边这个问题解决了么？

**Comment by NingerJohn** [comment]
> 谢谢提醒。我测试了下，现在确实有521的问题，应该是Mtime
> 网站已经更新了，用requests包测试，在header上加上cookie可以拿到返回值。但是scrapy这边测试还没有通过，不知道你那边这个问题解决了么？

无意间发现的，测试没问题。原理没细看。哈哈
https://blog.csdn.net/qq_33961117/article/details/92774953
